[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

# Define the path to buildspec.json relative to this script.
# (Assumes this script is in .github/scripts and buildspec.json is in the repo root.)
$buildspecPath = Join-Path $PSScriptRoot "../../buildspec.json"
if (!(Test-Path $buildspecPath)) {
    Write-Error "buildspec.json not found at $buildspecPath"
    exit 1
}

# Read and parse buildspec.json.
$buildspec = Get-Content -Path $buildspecPath -Raw | ConvertFrom-Json

# We want to use the 'prebuilt' dependency (which should contain libobs among other things).
if (-not $buildspec.dependencies.prebuilt) {
    Write-Error "No 'prebuilt' dependency found in buildspec.json"
    exit 1
}

$dep = $buildspec.dependencies.prebuilt

# Construct the file name and URL for Windows x64.
# We assume the asset is named "windows-deps-<version>-x64.zip"
$fileName = "windows-deps-$($dep.version)-x64.zip"
$url = "$($dep.baseUrl)/$($dep.version)/$fileName"

Write-Host "Downloading prebuilt obs-deps from $url ..."
Invoke-WebRequest -Uri $url -OutFile $fileName

# Verify the SHA256 hash (for Windows-x64)
$expectedHash = $dep.hashes."windows-x64"
$actualHash = (Get-FileHash -Algorithm SHA256 $fileName).Hash.ToLower()

if ($actualHash -ne $expectedHash.ToLower()) {
    Write-Error "Hash mismatch for $fileName. Expected: $expectedHash, Actual: $actualHash"
    exit 1
}

Write-Host "Hash validated."

# Define the destination folder where the archive will be extracted.
$destination = Join-Path $PSScriptRoot "../../dependencies/prebuilt"
if (Test-Path $destination) {
    Remove-Item -Recurse -Force $destination
}
Expand-Archive -Path $fileName -DestinationPath $destination

Write-Host "Extracted prebuilt obs-deps to $destination"
Write-Host "Extracted folder contents:"
Get-ChildItem -Path $destination -Recurse | Format-List FullName

# Determine the expected folder for libobs.
# This script assumes the archive extracts into a folder named "windows-deps-<version>-x64"
$filePrefix = "windows-deps-$($dep.version)-x64"
$libobsPath = Join-Path $destination "$filePrefix\lib\cmake\libobs"

if (Test-Path $libobsPath) {
    Write-Host "Setting libobs_DIR to $libobsPath"
    echo "libobs_DIR=$libobsPath" | Out-File -FilePath $env:GITHUB_ENV -Append
    echo "LIBOBS_INSTALL_DIR=$libobsPath" | Out-File -FilePath $env:GITHUB_ENV -Append
} else {
    Write-Warning "Could not find libobsConfig.cmake at expected location: $libobsPath"
    Write-Host "Falling back to building OBS from source to generate libobs and obs-frontend-api..."

    # Define a folder for the fallback OBS build.
    $obsSourceDir = Join-Path $env:GITHUB_WORKSPACE "obs-studio-fallback"

    # Clone the OBS Studio repository into the fallback folder.
    git clone --recursive https://github.com/obsproject/obs-studio.git $obsSourceDir

    Push-Location $obsSourceDir

    # Configure CMake with flags to install libobs and enable the frontend API.
    cmake -B build -A x64 -DCMAKE_INSTALL_PREFIX="$env:GITHUB_WORKSPACE\libobs_fallback" -DCMAKE_INSTALL_LIBDIR="lib/cmake/libobs" -DCMAKE_BUILD_TYPE=Release -DBUILD_BROWSER=OFF -DBUILD_OBSCONTROL=OFF -DENABLE_FRONTEND_API=ON

    # Build and install OBS Studio (or at least the necessary parts)
    cmake --build build --config Release --target install
    Pop-Location

    # Set fallback paths.
    $fallbackLibobsPath = Join-Path $env:GITHUB_WORKSPACE "libobs_fallback\lib\cmake\libobs"
    $fallbackFrontendApiPath = Join-Path $env:GITHUB_WORKSPACE "libobs_fallback\lib\cmake\obs-frontend-api"

    # Create the fallback config directories if they do not exist.
    if (!(Test-Path $fallbackLibobsPath)) {
        Write-Host "Fallback libobs config folder not found. Creating directory: $fallbackLibobsPath"
        New-Item -ItemType Directory -Force -Path $fallbackLibobsPath | Out-Null
    }
    if (!(Test-Path $fallbackFrontendApiPath)) {
        Write-Host "Fallback obs-frontend-api config folder not found. Creating directory: $fallbackFrontendApiPath"
        New-Item -ItemType Directory -Force -Path $fallbackFrontendApiPath | Out-Null
    }

    # Generate minimal libobsConfig.cmake if not present.
    $fallbackLibobsConfig = Join-Path $fallbackLibobsPath "libobsConfig.cmake"
    if (!(Test-Path $fallbackLibobsConfig)) {
        Write-Host "Generating minimal libobsConfig.cmake at $fallbackLibobsConfig"
        $libobsContent = @'
# Minimal libobsConfig.cmake generated by fetch-deps.ps1 fallback
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(libobs_INCLUDE_DIRS "${_IMPORT_PREFIX}/include")
set(libobs_LIBRARIES "${_IMPORT_PREFIX}/lib/obs.lib")
if(NOT TARGET OBS::libobs)
  add_library(OBS::libobs UNKNOWN IMPORTED)
  set_target_properties(OBS::libobs PROPERTIES
      INTERFACE_INCLUDE_DIRECTORIES "${libobs_INCLUDE_DIRS}"
      IMPORTED_LOCATION "${_IMPORT_PREFIX}/lib/obs.dll"
  )
endif()
'@
        $libobsContent | Out-File -FilePath $fallbackLibobsConfig -Encoding utf8
    }

    # Generate minimal obs-frontend-apiConfig.cmake if not present.
    $fallbackFrontendApiConfig = Join-Path $fallbackFrontendApiPath "obs-frontend-apiConfig.cmake"
    if (!(Test-Path $fallbackFrontendApiConfig)) {
        Write-Host "Generating minimal obs-frontend-apiConfig.cmake at $fallbackFrontendApiConfig"
        $frontendApiContent = @'
# Minimal obs-frontend-apiConfig.cmake generated by fetch-deps.ps1 fallback
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(obs_frontend_api_INCLUDE_DIRS "${_IMPORT_PREFIX}/include")
set(obs_frontend_api_LIBRARIES "${_IMPORT_PREFIX}/lib/obs-frontend-api.lib")
if(NOT TARGET OBS::obs-frontend-api)
  add_library(OBS::obs-frontend-api UNKNOWN IMPORTED)
  set_target_properties(OBS::obs-frontend-api PROPERTIES
      INTERFACE_INCLUDE_DIRECTORIES "${obs_frontend_api_INCLUDE_DIRS}"
      IMPORTED_LOCATION "${_IMPORT_PREFIX}/lib/obs-frontend-api.dll"
  )
endif()
'@
        $frontendApiContent | Out-File -FilePath $fallbackFrontendApiConfig -Encoding utf8
    }

    # Debug: List the contents of both fallback config directories.
    Write-Host "Listing fallback libobs config directory contents at $fallbackLibobsPath :"
    Get-ChildItem -Path $fallbackLibobsPath -Recurse | Format-List FullName

    Write-Host "Listing fallback obs-frontend-api config directory contents at $fallbackFrontendApiPath :"
    Get-ChildItem -Path $fallbackFrontendApiPath -Recurse | Format-List FullName

    # Verify and set environment variables.
    if ((Test-Path $fallbackLibobsConfig) -and (Test-Path $fallbackFrontendApiConfig)) {
        Write-Host "Fallback build successful. Setting environment variables..."
        echo "libobs_DIR=$fallbackLibobsPath" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "LIBOBS_INSTALL_DIR=$fallbackLibobsPath" | Out-File -FilePath $env:GITHUB_ENV -Append
        echo "obs-frontend-api_DIR=$fallbackFrontendApiPath" | Out-File -FilePath $env:GITHUB_ENV -Append
    } else {
        Write-Error "Fallback build did not produce the required configuration files."
        exit 1
    }
}